plugins {
    id 'com.android.application'
}

android {
    namespace 'com.velammal.buddy'
    compileSdk 34

    defaultConfig {
        applicationId 'com.velammal.buddy'
        minSdk 24          // Android 7.0 and newer (your Galaxy Tab has 8.1)
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
